### ISSUE TITLE
Upload an older version

### ISSUE THREAD

**Issue by isuruf** [conda-forge/gap-feedstock#1]
We have 4.8.6 atm, but `libgap` which is a dependency of `gap` needs `4.8.3`, so we'll have to upload an older version as well. @jakirkham, @ocefpaf, what should I do, here? upload to a different branch?

**Comment by jakirkham** [comment]
Yeah, add another branch on the feedstock for 4.8.3 and change the PR to point to that branch.

**Comment by isuruf** [comment]
Fixed via #2
