### ISSUE TITLE
Long path issue

### ISSUE THREAD

**Issue by isuruf** [conda-forge/gap-feedstock#3]
Following works
```
t=/tmp/asd/lb_env_plahold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
mkdir -p $t
conda install gap=4.8.3 -c conda-forge -p $t
source activate $t
gap
```

Following doesn't
```
t=/tmp/asd/lb_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/
mkdir -p $t
conda install gap=4.8.3 -c conda-forge -p $t
source activate $t
gap
```

Only difference is the path.

**Comment by isuruf** [comment]
@williamstein, @vbraun, I'd appreciate it if you have a look.

**Comment by isuruf** [comment]
I forgot to mention the error, here it is.
```
gap: hmm, I cannot find 'lib/init.g' maybe use option '-l <gaproot>'?
```
This doesn't happen if the prefix is a shorter path  or during conda build with a longer path.

**Comment by vbraun** [comment]
I think I saw that before and went with the shorter prefix. Upstream is here: https://github.com/gap-system

**Comment by isuruf** [comment]
Fixed in #4. I increased the size of the char buffer where the location of init.g was stored.

**Comment by vbraun** [comment]
Can you submit that patch to upstream?

**Comment by isuruf** [comment]
@vbraun, I opened an issue, https://github.com/gap-system/gap/issues/1171. I'm not entirely sure my patch wouldn't break anything else given I know nothing about gap. Had to update the patch and the new version is here, https://github.com/conda-forge/gap-feedstock/blob/v4.8.3/recipe/patches/long_path.patch
