### ISSUE TITLE
Package does not contain documentation

### ISSUE THREAD

**Issue by saraedum** [conda-forge/gap-feedstock#70]
Currently we drop all documentation because that's what SageMath used to do at some point (and we used their build script as a starting point it seems.)

We should probably install the documentation with `gap` but not with `gap-core` or something like that. (PRs welcome.)

**Comment by fingolfin** [comment]
Actually you don't drop all documentation, you just drop the GAP manuals (and hence the help system); but the reference manuals of all installed packages are untouched, with the exception of AGT...
